import type { BookPage } from "../../types";

/** Unità 1 · Piacere, sono io! — trang 2 (Si parte!, bài 3–5). Nội dung tự soạn. */
const page: BookPage = {
  id: "p002",
  number: 2,
  unit: "1",
  unitTitle: "Piacere, sono io!",
  addedOn: "2026-10-10",
  sideTab: { unit: "U1", title: "Piacere, sono io!" },
  title: "Si parte! · La scheda di iscrizione",
  runningHead: "Si parte!",
  blocks: [
    {
      type: "exercise",
      ex: {
        id: "p002-ex3",
        number: "3",
        icons: ["read", "match"],
        kind: "match",
        skill: "reading",
        instruction: "Abbiniamo le domande alle risposte di Tomás.",
        tr: { vi: "Nối các câu hỏi với câu trả lời của Tomás.", en: "Let's match the questions to Tomás's answers." },
        left: [
          { id: "1", text: "Come ti chiami?" },
          { id: "2", text: "Quanti anni hai?" },
          { id: "3", text: "Che lavoro fai?" },
          { id: "4", text: "Perché studi l'italiano?" },
          { id: "5", text: "Che cosa fai nel tempo libero?" },
        ],
        right: [
          { id: "a", text: "Faccio il cuoco." },
          { id: "b", text: "Gioco a calcetto e guardo vecchi film." },
          { id: "c", text: "Tomás Herrera." },
          { id: "d", text: "Ne ho ventotto." },
          { id: "e", text: "Perché voglio lavorare in un ristorante italiano." },
        ],
        given: { "1": "c" },
        rules: ["domande", "ne-quantita", "fare"],
        why: {
          "2": { rule: "ne-quantita", tr: { vi: "«**Quanti** anni hai?» hỏi số lượng → câu trả lời có con số: «**Ne** ho ventotto». *Ne* thay cho «anni» để khỏi lặp lại.", en: "«**Quanti** anni hai?» asks for a number → the answer has a number: «**Ne** ho ventotto». *Ne* replaces «anni» so it isn't repeated." } },
          "3": { rule: "fare", tr: { vi: "«Che lavoro **fai**?» dùng động từ *fare* → trả lời cũng bằng *fare*: «**Faccio il** cuoco» (fare + mạo từ + nghề).", en: "«Che lavoro **fai**?» uses *fare* → answer with *fare* too: «**Faccio il** cuoco» (fare + article + job)." } },
          "4": { rule: "domande", tr: { vi: "Hỏi bằng «**Perché**…?» (tại sao) → trả lời cũng bắt đầu bằng «**Perché**…» (vì).", en: "A «**Perché**…?» (why) question → the answer also starts with «**Perché**…» (because)." } },
          "5": { rule: "domande", tr: { vi: "«Che cosa **fai** nel tempo libero?» hỏi về hoạt động → câu trả lời là các động từ chia ngôi io: «**gioco**… **guardo**…».", en: "«Che cosa **fai** nel tempo libero?» asks about activities → the answer has io-form verbs: «**gioco**… **guardo**…»." } },
        },
        answer: { "1": "c", "2": "d", "3": "a", "4": "e", "5": "b" },
      },
    },
    {
      type: "exercise",
      ex: {
        id: "p002-ex4",
        number: "4",
        icons: ["write"],
        kind: "form",
        skill: "writing",
        formStyle: "corso",
        formTitle: "SCUOLA “PAROLA VIVA” · BOLOGNA",
        formSubtitle: "SCHEDA DI ISCRIZIONE",
        instruction: "Scriviamo: compiliamo la scheda con i nostri dati.",
        tr: { vi: "Cùng viết: điền phiếu với thông tin của bạn.", en: "Let's write: fill in the form with our details." },
        items: [
          { id: "nome", label: "Nome e cognome:", col: 1 },
          { id: "nascita", label: "Nato/a a … il …:", col: 1 },
          { id: "naz", label: "Paese di provenienza:", col: 1 },
          { id: "lavoro", label: "Studio / lavoro:", col: 1 },
          { id: "lingue", label: "Lingue che parlo:", col: 1 },
          { id: "q1", label: "Da quanto tempo studi l'italiano?", col: 2, section: "Due parole su di te", sectionNote: "Rispondi con una o due frasi:" },
          { id: "q2", label: "Che cosa vuoi migliorare di più? (parlare, ascoltare, scrivere, leggere…)", col: 2, lines: 2 },
          { id: "q3", label: "Una cosa dell'Italia che ami e una che non capisci ancora:", col: 2, lines: 2 },
          { id: "corso", label: "Corso scelto:", col: "foot", options: ["mattina", "pomeriggio", "sera"], optionCols: 3 },
        ],
      },
    },
    {
      type: "exercise",
      ex: {
        id: "p002-ex5",
        number: "5",
        icons: ["write"],
        kind: "fill",
        skill: "grammar",
        instruction: "Completiamo con i verbi chiamarsi, essere, avere, fare al presente.",
        example: { q: "1. Io (chiamarsi) ___ Hoa.", a: "Io ***mi chiamo*** Hoa." },
        tr: { vi: "Hoàn thành câu với các động từ chiamarsi, essere, avere, fare ở thì hiện tại.", en: "Let's complete with the verbs chiamarsi, essere, avere, fare in the present." },
        items: [
          { id: "2", prompt: "2. Tomás (essere) ___ argentino e (fare) ___ il cuoco.", answers: ["è", "fa"] },
          { id: "3", prompt: "3. Noi (avere) ___ lezione tutte le mattine alle nove.", answers: ["abbiamo"] },
          { id: "4", prompt: "4. Come (chiamarsi) ___ la vostra insegnante?", answers: ["si chiama"] },
          { id: "5", prompt: "5. Voi di dove (essere) ___?", answers: ["siete"] },
          { id: "6", prompt: "6. Hoa e Tomás (avere) ___ quasi la stessa età.", answers: ["hanno"] },
        ],
        rules: ["essere", "avere", "fare", "chiamarsi"],
        why: {
          "2": { rule: "essere", tr: { vi: "Chủ ngữ **Tomás** = ngôi thứ ba số ít (lui). Quốc tịch dùng *essere* → «**è** argentino» (có dấu: è = là). Nghề dùng *fare* + mạo từ → «**fa** il cuoco».", en: "Subject **Tomás** = third person singular (lui). Nationality takes *essere* → «**è** argentino» (with accent: è = is). Job takes *fare* + article → «**fa** il cuoco»." } },
          "3": { rule: "avere", tr: { vi: "Chủ ngữ **noi** → avere chia là «**abbiamo**». Nhớ: *avere lezione* = có giờ học.", en: "Subject **noi** → avere becomes «**abbiamo**». Remember: *avere lezione* = to have class." } },
          "4": { rule: "chiamarsi", tr: { vi: "Chủ ngữ là «**la vostra insegnante**» (một người → lei) chứ không phải «voi». Động từ phản thân → «**si chiama**».", en: "The subject is «**la vostra insegnante**» (one person → lei), not «voi». Reflexive verb → «**si chiama**»." } },
          "5": { rule: "essere", tr: { vi: "Chủ ngữ **voi** → essere chia là «**siete**». «Di dove siete?» = Các bạn từ đâu đến?", en: "Subject **voi** → essere becomes «**siete**». «Di dove siete?» = Where are you all from?" } },
          "6": { rule: "avere", tr: { vi: "**Hoa e Tomás** = hai người → loro → «**hanno**». Nói về tuổi (età) tiếng Ý dùng *avere*, không dùng essere.", en: "**Hoa e Tomás** = two people → loro → «**hanno**». Age (età) in Italian takes *avere*, not essere." } },
        },
      },
    },
    { type: "theory", text: "! ATTENZIONE!\n- Con un amico: | **Ciao, come ti chiami?** — **Di dove sei?**\n- Con una persona che non conosciamo: | **Buongiorno, come si chiama?** — **Di dov'è?**" },
  ],
};

export default page;
