import type { BookPage } from "../../types";

/** Unità 1 · Entriamo in Italia! — trang 3 (Cominciamo, bài 3–4). */
const page: BookPage = {
  id: "p003",
  number: 3,
  unit: "1",
  unitTitle: "Entriamo in Italia!",
  title: "Cominciamo · Moduli di iscrizione",
  addedOn: "2026-10-03",
  runningHead: "Cominciamo",
  sideTab: { unit: "U1", title: "Entriamo in Italia!" },
  blocks: [
    {
      type: "exercise",
      ex: {
        id: "p003-ex3",
        number: "3",
        icons: ["read", "write"],
        kind: "form",
        skill: "writing",
        formStyle: "corso",
        formTitle: "CORSO DI LINGUA",
        formSubtitle: "MODULO DI ISCRIZIONE",
        instruction: "Leggiamo e completiamo la domanda di iscrizione.",
        tr: { vi: "Đọc và hoàn thành đơn đăng ký.", en: "Let's read and complete the application form." },
        items: [
          { id: "nome", label: "Nome:", col: 1 },
          { id: "cognome", label: "Cognome:", col: 1 },
          { id: "nascita", label: "Data di nascita:", col: 1 },
          { id: "luogo", label: "Luogo di nascita:", col: 1 },
          { id: "naz", label: "Nazionalità:", col: 1 },
          { id: "prof", label: "Professione:", col: 1 },
          { id: "q1", label: "1. Quante lingue conosce?", col: 1 },
          { id: "q2", label: "2. Dove ha studiato la lingua italiana? Per quanto tempo?", col: 1, lines: 2 },
          { id: "q3", label: "3. Perché studia l'italiano?", col: 1 },
          { id: "q4", label: "4. Che cosa si aspetta da un corso di lingua italiana?", col: 1 },
          {
            id: "q5",
            label:
              "5. Che cosa le interessa di più approfondire fra i seguenti aspetti della lingua italiana: la grammatica, la conversazione, il lessico, la pronuncia, l'ascolto, la lettura o la scrittura?",
            col: 2,
            lines: 2,
          },
          { id: "q6", label: "6. Quali sono gli aspetti della cultura italiana che le piacciono di più?", col: 2, lines: 2 },
          {
            id: "t1",
            label: "1. Ha mai visto un film italiano? Quale?",
            col: 2,
            section: "Volete seguire dei corsi su temi specifici?",
            sectionNote: "Allora rispondete alle seguenti domande:",
          },
          { id: "t2", label: "2. Ha mai letto un libro di un autore italiano? Quale?", col: 2 },
          { id: "t3", label: "3. Conosce l'arte italiana? Qual è il suo periodo preferito?", col: 2, lines: 2 },
          { id: "t4", label: "4. Ascolta musica italiana? Che genere? Qual è il suo cantante preferito?", col: 2, lines: 2 },
        ],
      },
    },
    {
      type: "audio",
      track: "1 · 4",
      src: "audio/u1-p3-ex4.mp3",
      autoTranscript: true,
      transcript: [
        "Mark: Buongiorno. Vorrei un modulo di iscrizione per i corsi di italiano.",
        "Segreteria: Sì, subito. Devi riempirlo con i tuoi dati e poi consegnarlo all'ufficio iscrizioni. Hai bisogno di aiuto?",
        "Mark: Sì, grazie.",
        "Segreteria: Va bene. Allora, devi scrivere il tuo nome, l'indirizzo, la data e il luogo di nascita.",
        "Mark: Ok. Il nome è Mark Smith. Sono nato a Washington il 20 aprile 1985. Ma devo scrivere l'indirizzo di Siena?",
        "Segreteria: No, devi mettere l'indirizzo della tua città e il numero di telefono.",
        "Mark: Ok. 20852 Grosvenor Park, Washington DC. E il mio numero è 202 345 2228. Devo anche scrivere qual è la mia professione?",
        "Segreteria: Sì, e anche che cosa hai studiato nel tuo Paese.",
        "Mark: Molto bene. Sono uno studente e vorrei frequentare un corso all'Università per Stranieri. Negli Stati Uniti, all'università, ho studiato arte.",
        "Segreteria: Hai anche un recapito qui a Siena?",
        "Mark: No, ancora non ho un recapito in città, perché devo cercare un appartamento.",
        "Segreteria: Ah, ho capito. Puoi mandare comunque un fax al numero 0577 240111 quando avrai tutto pronto. Hai frequentato prima un corso qui all'Università per Stranieri?",
        "Mark: No, questa è la prima volta.",
        "Segreteria: Che tipo di corso ti interessa?",
        "Mark: Vorrei fare un corso ordinario di lingua e cultura italiana.",
        "Segreteria: Che livello?",
        "Mark: Livello tre.",
        "Segreteria: Perfetto! Non dimenticare di firmare il modulo e di scrivere la data di oggi: 10 settembre 2007.",
      ].join("\n"),
    },
    {
      type: "exercise",
      ex: {
        id: "p003-ex4",
        number: "4",
        icons: ["listen", "write"],
        kind: "form",
        skill: "listening",
        refText: "audio",
        formStyle: "siena",
        formTitle: "UNIVERSITÀ PER STRANIERI DI SIENA",
        instruction: "Ascoltiamo e completiamo il modulo.",
        tr: { vi: "Nghe và hoàn thành mẫu đơn.", en: "Let's listen and complete the form." },
        items: [
          { id: "cognome", label: "Cognome", col: 1, given: "Smith" },
          { id: "nome", label: "Nome", col: 1, answers: "Mark" },
          { id: "nascita", label: "Data di nascita", col: 1, answers: "20 aprile 1985|20/04/1985|20/4/1985|20-04-1985|20.04.1985" },
          { id: "luogo", label: "Luogo di nascita", col: 1, answers: "Washington|Washington DC" },
          { id: "citt", label: "Cittadinanza", col: 1, answers: "americana|statunitense|americano|USA|Stati Uniti" },
          { id: "res", label: "Residenza/indirizzo", col: 1, answers: "20852 Grosvenor Park, Washington DC|20852 Grosvenor Park" },
          { id: "tel", label: "Telefono", col: 1, answers: "202 345 2228" },
          { id: "prof", label: "Professione", col: 1, answers: "studente" },
          { id: "studi", label: "Studi compiuti", col: 1, answers: "arte|ha studiato arte|arte all'università" },
          { id: "recapito", label: "Recapito a Siena", col: 1, answers: "nessuno|no|non ha un recapito|—|-" },
          {
            id: "freq",
            label: "Ha mai frequentato un corso all'Università per Stranieri di Siena?",
            col: 2,
            options: ["sì", "no"],
            answer: 1,
            optionCols: 2,
          },
          {
            id: "tipo",
            label: "Che tipo di corso preferisce?",
            col: 2,
            options: ["corso ordinario di lingua e cultura italiana", "corso intensivo di lingua italiana"],
            answer: 0,
            optionCols: 1,
          },
          {
            id: "livello",
            label: "Livello del corso richiesto:",
            col: 2,
            options: ["Uno", "Due", "Tre", "Quattro", "Cinque", "Sei"],
            answer: 2,
            optionCols: 3,
          },
          { id: "data", label: "Data", col: "foot", answers: "10 settembre 2007|10/09/2007|10/9/2007|10-09-2007|10.09.2007" },
          { id: "firma", label: "Firma", col: "foot", answers: "Mark Smith|Smith" },
        ],
      },
    },
  ],
};

export default page;
