import type { BookPage } from "../../types";

/** Unità 1 · Entriamo in Italia! — trang 6 (Osserviamo bene, bài 8). */
const page: BookPage = {
  id: "p006",
  number: 6,
  unit: "1",
  unitTitle: "Entriamo in Italia!",
  title: "Osserviamo bene · Gli stranieri e l'Italia",
  addedOn: "2026-10-03",
  runningHead: "Osserviamo bene",
  banner: "GLI STRANIERI E L'ITALIA",
  sideTab: { unit: "U1", title: "Entriamo in Italia!" },
  blocks: [
    {
      type: "audio",
      track: "1 · 8",
      src: "audio/u1-p6-ex8.mp3",
      autoTranscript: true,
      transcript: [
        "Giornalista: Signora Bo, l'Italia attira i turisti cinesi?",
        "Yunjie: Sì, le assicuro che i nostri itinerari europei prevedono almeno tre giorni in Italia.",
        "Giornalista: Ai vostri clienti quali città proponete di visitare?",
        "Yunjie: Gli consigliamo soprattutto Roma, Firenze e Venezia. Solo alcuni tour prevedono anche Napoli e Pompei.",
        "Giornalista: E le città d'arte come Siena, Lucca, Assisi?",
        "Yunjie: Non le abbiamo nei nostri programmi, perché i turisti cinesi preferiscono le grandi città famose.",
        "Giornalista: Mi dica, ai cinesi piace la cucina italiana?",
        "Yunjie: Sì, gli piace molto, ma i vostri ristoranti hanno prezzi molto cari, perciò abbiamo fatto delle convenzioni con ristoranti cinesi nelle città europee.",
        "Giornalista: Signor Berg, lei per motivi di lavoro ha viaggiato molto in Italia: quale città preferisce?",
        "Joel: Preferisco Firenze: mi piace visitarla tutte le volte che vengo in Italia; mi piace anche fermarmi nella campagna toscana durante l'estate con la mia famiglia.",
        "Giornalista: Dove fate shopping di solito?",
        "Joel: Per i vestiti andiamo a Milano. Ci fermiamo, poi, qualche volta a Venezia, dove compriamo oggetti molto belli per la nostra casa.",
        "Giornalista: Che cosa non le piace dell'Italia?",
        "Joel: Non amo il traffico e la disorganizzazione delle grandi città!",
        "Giornalista: Tanya, da quanto tempo lei è in Italia?",
        "Tanya: Vivo e lavoro a Milano dal 1988.",
        "Giornalista: Le piace Milano?",
        "Tanya: All'inizio è stato difficile vivere a Milano: sto imparando ora ad amarla!",
        "Giornalista: Quali regioni visita più volentieri?",
        "Tanya: L'Umbria e la Toscana, anche se durante l'estate mi piacciono di meno perché sono piene di turisti!",
        "Giornalista: Cosa pensa degli italiani?",
        "Tanya: Li ammiro molto per il loro carattere aperto: è molto simile a quello degli israeliani!",
        "Giornalista: Cosa ama di più del nostro paese?",
        "Tanya: La cucina e lo shopping nei mercatini!",
      ].join("\n"),
    },
    {
      type: "exercise",
      ex: {
        id: "p006-ex8",
        number: "8",
        icons: ["listen", "write"],
        kind: "cloze",
        skill: "listening",
        refText: "audio",
        instruction: "Ascoltiamo e completiamo i dialoghi con i pronomi.",
        tr: { vi: "Nghe và hoàn thành các đoạn hội thoại với đại từ.", en: "Let's listen and complete the dialogues with pronouns." },
        parts: [
          {
            boxed: true,
            title: "A. Yunjie Bo, cinese, impiegata della Shangai Fasco International Tour.",
            image: { photo: "Chinese businesswoman laptop office", alt: "Yunjie Bo al computer", side: "right", width: 24 },
            text: [
              "• Signora Bo, l'Italia attira i turisti cinesi?",
              "○ Sì, {{=le}} assicuro che i nostri itinerari europei prevedono almeno tre giorni in Italia.",
              "• Ai vostri clienti quali città proponete di visitare?",
              "○ {{Gli|A loro}} consigliamo soprattutto Roma, Firenze, Venezia. Solo alcuni tour prevedono anche Napoli e Pompei.",
              "• E le città d'arte come Siena, Lucca, Assisi?",
              "○ Non {{le}} abbiamo nei nostri programmi perché i turisti cinesi preferiscono le grandi città famose.",
              "• {{Mi}} dica, ai cinesi piace la cucina italiana?",
              "○ Sì, {{gli|a loro}} piace molto, ma i vostri ristoranti hanno prezzi molto cari, perciò abbiamo fatto delle convenzioni con ristoranti cinesi nelle città europee.",
            ].join("\n"),
          },
          {
            boxed: true,
            title: "B. Joel Berg, svedese, impiegato alla Benetton.",
            image: { photo: "businessman blue shirt tie smiling", alt: "Joel Berg", side: "right", width: 24 },
            text: [
              "• Signor Berg, lei per motivi di lavoro ha viaggiato molto in Italia: quale città preferisce?",
              "○ Preferisco Firenze: {{mi}} piace visitarla tutte le volte che vengo in Italia; {{mi}} piace anche fermar{{mi}} nella campagna toscana durante l'estate con la mia famiglia.",
              "• Dove fate shopping di solito?",
              "○ Per i vestiti andiamo a Milano. {{Ci}} fermiamo, poi, qualche volta a Venezia, dove compriamo oggetti molto belli per la nostra casa.",
              "• Che cosa non {{le}} piace dell'Italia?",
              "○ Non amo il traffico e la disorganizzazione delle grandi città!",
            ].join("\n"),
          },
          {
            boxed: true,
            columns: 2,
            title: "C. Tanya Jones, israeliana, stilista.",
            image: { photo: "woman fashion designer boutique", alt: "Tanya Jones nel suo negozio", side: "left", width: 22 },
            text: [
              "• Tanya, da quanto tempo lei è in Italia?",
              "○ Vivo e lavoro a Milano dal 1988.",
              "• {{Le}} piace Milano?",
              "○ All'inizio è stato difficile vivere a Milano: sto imparando ora ad amar{{la}}!",
              "• Quali regioni visita più volentieri?",
              "○ L'Umbria e la Toscana, anche se durante l'estate {{mi}} piacciono di meno perché sono piene di turisti!",
              "• Cosa pensa degli italiani?",
              "○ {{Li}} ammiro molto per il loro carattere aperto: è molto simile a quello degli israeliani!",
              "• Cosa ama di più del nostro paese?",
              "○ La cucina e lo shopping nei mercatini!",
            ].join("\n"),
          },
        ],
      },
    },
  ],
};

export default page;
