import type { BookPage } from "../../types";

/** Unità 2 · Ieri e oggi in famiglia — trang 26 (Osserviamo bene, bài 6: l'imperfetto). */
const page: BookPage = {
  id: "p026",
  number: 26,
  unit: "2",
  unitTitle: "Ieri e oggi in famiglia",
  title: "Osserviamo bene · L'imperfetto indicativo",
  addedOn: "2026-10-06",
  runningHead: "Osserviamo bene",
  banner: "IO ERO...",
  sideTab: { unit: "U2", title: "Ieri e oggi in famiglia" },
  blocks: [
    {
      type: "exercise",
      ex: {
        id: "p026-ex6a",
        number: "6",
        label: "A",
        icons: ["read"],
        kind: "speak",
        skill: "reading",
        instruction: "Leggiamo.",
        subtitle: "Usiamo l'imperfetto indicativo per…",
        tr: { vi: "Cùng đọc: ta dùng thì imperfetto để…", en: "Let's read: we use the imperfetto to…" },
        items: [],
      },
    },
    {
      type: "gridTable",
      head: [
        "descrivere situazioni, persone, sentimenti, sensazioni, paesaggi, tempo",
        "descrivere azioni non finite",
        "descrivere azioni abituali",
        "descrivere azioni contemporanee",
        "fare una richiesta gentile",
      ],
      rows: [
        [
          "In estate **andavo** al mare con i miei.\n\nGiorgio **aveva** i capelli neri.\n\n**Amavo** mio marito con tutto il cuore.\n\n**Sentivamo** sempre freddo a casa di Piero.\n\nMilano **era** bellissima di notte.\n\n**Nevicava** spesso in montagna.",
          "Caterina **parlava** e tutti **ascoltavano**.\n\n• Ieri sera alle 10 che **facevi**?\n○ **Stavo** ancora cenando.\n\nNon **volevo** giocare a tennis perché **avevo** un dolore al braccio.\n\nSuo padre **lavorava** in fabbrica.",
          "Quando **vivevamo** a Roma, **uscivamo** tutte le sere.\n\nDa piccoli **andavano** al mare ogni estate.\n\nAlessandro **studiava** sempre con Giulio.",
          "Mentre Luisa **scriveva**, Beatrice **leggeva** il giornale.\n\nMentre **guardavo** la TV **bevevo** il caffè.\n\nMentre il professore **spiegava**, gli studenti **stavano** attenti.",
          "Scusami, **volevo** chiederti un favore…\n\nBuongiorno, **volevo** una carta telefonica da trenta euro.",
        ],
      ],
    },
    {
      type: "exercise",
      ex: {
        id: "p026-ex6b",
        label: "B",
        icons: ["match", "write"],
        kind: "match",
        skill: "grammar",
        instruction: "Abbiniamo e completiamo le frasi con i verbi all'imperfetto.",
        tr: { vi: "Nối và hoàn thành câu với động từ ở thì imperfetto.", en: "Let's match and complete the sentences with the verbs in the imperfetto." },
        left: [
          { id: "1", text: "Chi c'(essere) era al compleanno di Filippo?" },
          { id: "2", text: "Siccome (noi, essere) …… stanchi," },
          { id: "3", text: "Quando (io, uscire) …… dall'ufficio," },
          { id: "4", text: "Cosa (tu, fare) …… dopo la scuola?" },
          { id: "5", text: "Come (essere) …… il mare in Sardegna?" },
          { id: "6", text: "Chi (preparare) …… la cena a casa tua?" },
          { id: "7", text: "Allora, che vestito (avere) …… la sposa?" },
          { id: "8", text: "Mentre Barbara (vestirsi) ……," },
          { id: "9", text: "Buongiorno, signora: che cosa desidera?" },
          { id: "10", text: "Che cosa (tu, volere) …… ?" },
        ],
        right: [
          { id: "a", text: "Michele (farsi) …… la doccia e (prepararsi) ……" },
          { id: "b", text: "(essere) …… sempre la nonna perché (cucinare) …… benissimo." },
          { id: "c", text: "Molto particolare e (portare) …… anche un velo lungo." },
          { id: "d", text: "(Volere) …… un po' di affettati e del pane." },
          { id: "e", text: "Mi (servire) …… una penna." },
          { id: "f", text: "I suoi amici e anche sua cugina." },
          { id: "g", text: "(io, prendere) …… sempre l'autobus." },
          { id: "h", text: "Di solito (uscire) …… con i miei amici e (guardare) …… la TV." },
          { id: "i", text: "non (volere) …… andare a casa a piedi." },
          { id: "l", text: "Stupendo! (avere) …… un colore trasparente e la sabbia (essere) …… bianchissima." },
        ],
        given: { "1": "f" },
        answer: { "1": "f", "2": "i", "3": "g", "4": "h", "5": "l", "6": "b", "7": "c", "8": "a", "9": "d", "10": "e" },
      },
    },
    {
      type: "exercise",
      ex: {
        id: "p026-ex6b-verbi",
        icons: ["write"],
        kind: "fill",
        skill: "grammar",
        instruction: "Completiamo con i verbi all'imperfetto.",
        tr: { vi: "Điền động từ ở thì imperfetto vào các câu trên.", en: "Fill in the verbs in the imperfetto." },
        items: [
          { id: "2", prompt: "2. Siccome (*noi, essere*) ___ stanchi, (i) non (*volere*) ___ andare a casa a piedi.", answers: ["eravamo", "volevamo"] },
          { id: "3", prompt: "3. Quando (*io, uscire*) ___ dall'ufficio, (g) (*io, prendere*) ___ sempre l'autobus.", answers: ["uscivo", "prendevo"] },
          { id: "4", prompt: "4. Cosa (*tu, fare*) ___ dopo la scuola? (h) Di solito (*uscire*) ___ con i miei amici e (*guardare*) ___ la TV.", answers: ["facevi", "uscivo", "guardavo"] },
          { id: "5", prompt: "5. Come (*essere*) ___ il mare in Sardegna? (l) Stupendo! (*avere*) ___ un colore trasparente e la sabbia (*essere*) ___ bianchissima.", answers: ["era", "Aveva", "era"] },
          { id: "6", prompt: "6. Chi (*preparare*) ___ la cena a casa tua? (b) (*essere*) ___ sempre la nonna perché (*cucinare*) ___ benissimo.", answers: ["preparava", "Era", "cucinava"] },
          { id: "7", prompt: "7. Allora, che vestito (*avere*) ___ la sposa? (c) Molto particolare e (*portare*) ___ anche un velo lungo.", answers: ["aveva", "portava"] },
          { id: "8", prompt: "8. Mentre Barbara (*vestirsi*) ___, (a) Michele (*farsi*) ___ la doccia e (*prepararsi*) ___.", answers: ["si vestiva", "si faceva", "si preparava"] },
          { id: "9", prompt: "9. Buongiorno, signora: che cosa desidera? (d) (*Volere*) ___ un po' di affettati e del pane.", answers: ["Volevo"] },
          { id: "10", prompt: "10. Che cosa (*tu, volere*) ___? (e) Mi (*servire*) ___ una penna.", answers: ["volevi", "serviva"] },
        ],
      },
    },
  ],
};

export default page;
