import type { BookPage } from "../../types";

/** Unità 3 · Ti piace leggere? — trang 42 (Cominciamo, bài 1–2). */
const page: BookPage = {
  id: "p042",
  number: 42,
  unit: "3",
  unitTitle: "Ti piace leggere?",
  addedOn: "2026-10-07",
  title: "Cominciamo · Il mio libro preferito",
  blocks: [
    {
      type: "unitHeader",
      unit: "3",
      title: "Ti piace leggere?",
      intro: "In questa Unità impariamo a:",
      goals: [
        { it: "conoscere alcuni brani di letteratura", tr: { vi: "làm quen với vài trích đoạn văn học", en: "get to know some literary passages" } },
        { it: "dare consigli", tr: { vi: "đưa ra lời khuyên", en: "give advice" } },
        { it: "fare richieste in modo cortese", tr: { vi: "yêu cầu một cách lịch sự", en: "make polite requests" } },
        { it: "esprimere desideri", tr: { vi: "bày tỏ mong muốn", en: "express wishes" } },
      ],
    },
    { type: "sectionTitle", text: "Cominciamo", banner: "IL MIO LIBRO PREFERITO" },
    {
      type: "audio",
      src: "audio/u3-p42-ex1.mp3",
      autoTranscript: true,
      transcript: [
        "Ascolto 1",
        "Sara: Ciao, Michele, che cosa hai fatto ieri sera?",
        "Michele: Ho affittato una videocassetta e ho visto, insieme a Sara, un film con Penélope Cruz e Sergio Castellitto.",
        "Sara: Vi è piaciuto?",
        "Michele: Sì, molto. Dovresti guardarlo. Il film è tratto dal libro di Margaret Mazzantini, Non ti muovere. Lo hai letto?",
        "Sara: No, ma mi piacerebbe. Recentemente ho letto un libro molto interessante, Memoriale del convento di José Saramago, il famoso scrittore portoghese che ha vinto il premio Nobel per la letteratura.",
        "Michele: Bene, vorrei leggerlo anch'io. Mi presteresti questo libro?",
        "Sara: D'accordo.",
        "Ascolto 2",
        "Maestra: Allora, Riccardo, qual è il tuo libro preferito?",
        "Riccardo: Fino all'anno scorso il mio libro preferito era Pinocchio di Collodi, ma poi la maestra mi ha suggerito di leggere Il piccolo principe di Antoine de Saint-Exupéry, che mi ha veramente colpito. E il tuo libro preferito qual è?",
        "Amica: La gabbianella e il gatto di Luis Sepúlveda.",
        "Ascolto 3",
        "Libraio: Buongiorno, signora. Desidera?",
        "Signora: Vorrei regalare un libro a mio nipote. Potrebbe suggerirmi qualcosa?",
        "Libraio: Certo. Quanti anni ha suo nipote?",
        "Signora: Diciannove.",
        "Libraio: Bene, allora, se gli piacciono i romanzi, potrei suggerirle Il nome della rosa di Umberto Eco.",
        "Signora: Mmm, forse lo ha già letto.",
        "Libraio: Oppure Un uomo, il famoso libro di Oriana Fallaci, che racconta una storia avvincente ed emozionante.",
        "Signora: E cosa pensa del Codice da Vinci di Dan Brown? Ho letto molte recensioni su quest'opera e so che ha avuto un grande successo.",
        "Libraio: È vero, lo abbiamo venduto molto. È un libro pieno di mistero e di suspense.",
        "Signora: Bene, allora lo prendo.",
      ].join("\n"),
    },
    {
      type: "exercise",
      ex: {
        id: "p042-ex1",
        number: "1",
        icons: ["listen", "match"],
        kind: "match",
        skill: "listening",
        refText: "audio",
        instruction: "Ascoltiamo i dialoghi e abbiniamo i nomi degli autori ai titoli dei libri.",
        tr: { vi: "Nghe các đoạn hội thoại và nối tên tác giả với tên sách.", en: "Let's listen to the dialogues and match the authors to the book titles." },
        left: [
          { id: "1", text: "Oriana Fallaci" },
          { id: "2", text: "Luis Sepúlveda" },
          { id: "3", text: "Dan Brown" },
          { id: "4", text: "Carlo Collodi" },
          { id: "5", text: "Antoine de Saint-Exupéry" },
          { id: "6", text: "José Saramago" },
          { id: "7", text: "Umberto Eco" },
          { id: "8", text: "Margaret Mazzantini" },
        ],
        right: [
          { id: "a", text: "Il Codice Da Vinci" },
          { id: "b", text: "Non ti muovere" },
          { id: "c", text: "Il nome della rosa" },
          { id: "d", text: "Memoriale del convento" },
          { id: "e", text: "Pinocchio" },
          { id: "f", text: "La gabbianella e il gatto" },
          { id: "g", text: "Il piccolo principe" },
          { id: "h", text: "Un uomo" },
        ],
        answer: { "1": "h", "2": "f", "3": "a", "4": "e", "5": "g", "6": "d", "7": "c", "8": "b" },
      },
    },
    { type: "photo", src: "images/u3/p42-libri.jpg", alt: "Le copertine di otto libri numerati da 1 a 8" },
    {
      type: "exercise",
      ex: {
        id: "p042-ex2",
        number: "2",
        icons: ["speak"],
        kind: "speak",
        skill: "speaking",
        instruction: "Parliamo: rispondiamo alle domande.",
        tr: { vi: "Cùng nói: trả lời các câu hỏi.", en: "Let's talk: answer the questions." },
        items: [
          { id: "1", prompt: "Quanto tempo dedicate alla lettura?" },
          { id: "2", prompt: "Quale genere di libri preferite?" },
          { id: "3", prompt: "Qual è il vostro autore preferito?" },
          { id: "4", prompt: "Avete mai letto libri di autori italiani? Quali?" },
          { id: "5", prompt: "Avete letto qualche libro fra quelli dell'attività 1?" },
          { id: "6", prompt: "Quale libro avete letto di recente? Qual è la trama?" },
        ],
      },
    },
  ],
};

export default page;
