import type { BookPage } from "../../types";

/** Unità 3 · Ti piace leggere? — trang 58 (Scrittura e pronuncia, bài 18–21). */
const page: BookPage = {
  id: "p058",
  number: 58,
  unit: "3",
  unitTitle: "Ti piace leggere?",
  addedOn: "2026-10-07",
  sideTab: { unit: "U3", color: "#d8333a" },
  title: "Scrittura e pronuncia · Il condizionale, la punteggiatura",
  runningHead: "Scrittura e pronuncia",
  blocks: [
    { type: "sectionTitle", text: "Scrittura e pronuncia" },
    {
      type: "audio",
      src: "audio/u3-p58-ex18.mp3",
      title: "18",
      autoTranscript: true,
      transcript: "1. terrebbero · 2. andrebbe · 3. vorrebbe · 4. faremmo · 5. verreste · 6. rimarrei · 7. vivrei · 8. verresti",
    },
    {
      type: "exercise",
      ex: {
        id: "p058-ex18",
        inline: true,
        number: "18",
        icons: ["listen", "write"],
        kind: "choice",
        skill: "listening",
        refText: "audio",
        instruction: "Ascoltiamo e sottolineiamo la parola giusta.",
        tr: { vi: "Nghe và gạch chân từ đúng.", en: "Let's listen and underline the right word." },
        items: [
          { id: "1", prompt: "", options: ["terrebbero", "terebbero", "tenrebero"], answer: 0 },
          { id: "2", prompt: "", options: ["anderebbe", "andrebbe", "andrebe"], answer: 1 },
          { id: "3", prompt: "", options: ["vorrebbe", "volerebbe", "vorebbe"], answer: 0 },
          { id: "4", prompt: "", options: ["faremo", "faremmo", "farremmo"], answer: 1 },
          { id: "5", prompt: "", options: ["verresti", "vereste", "verreste"], answer: 2 },
          { id: "6", prompt: "", options: ["rimarei", "rimarrei", "rimanerei"], answer: 1 },
          { id: "7", prompt: "", options: ["viverei", "vivvrei", "vivrei"], answer: 2 },
          { id: "8", prompt: "", options: ["verresti", "veresti", "vedresti"], answer: 0 },
        ],
      },
    },
    {
      type: "exercise",
      ex: {
        id: "p058-ex19",
        number: "19",
        icons: ["write"],
        kind: "fill",
        skill: "grammar",
        instruction: "Scriviamo: correggiamo se necessario.",
        example: { q: "1. edizzione", a: "edizione" },
        tr: { vi: "Cùng viết: sửa lỗi chính tả nếu cần (nếu từ đã đúng, chép lại).", en: "Let's write: correct the spelling if necessary (if the word is right, copy it)." },
        items: [
          { id: "2", prompt: "pagina → ___", answers: ["pagina"] },
          { id: "3", prompt: "recenzione → ___", answers: ["recensione"] },
          { id: "4", prompt: "sfoliare → ___", answers: ["sfogliare"] },
          { id: "5", prompt: "stanpa → ___", answers: ["stampa"] },
          { id: "6", prompt: "fumetto → ___", answers: ["fumetto"] },
          { id: "7", prompt: "scenza → ___", answers: ["scienza"] },
          { id: "8", prompt: "conoscenza → ___", answers: ["conoscenza"] },
        ],
      },
    },
    {
      type: "audio",
      src: "audio/u3-p58-ex20.mp3",
      title: "20",
      autoTranscript: true,
      transcript: "1. racconto · 2. riassunto · 3. passeggiare · 4. trascorrere · 5. viaggiare · 6. lettura · 7. spettacolo · 8. interessante · 9. caratteristico · 10. terribile · 11. scrittore · 12. abbonamento · 13. parrucchiere · 14. appassionarsi · 15. preoccupazione",
    },
    {
      type: "exercise",
      ex: {
        id: "p058-ex20",
        number: "20",
        icons: ["listen", "write"],
        kind: "write",
        skill: "listening",
        refText: "audio",
        instruction: "Ascoltiamo e scriviamo le parole.",
        tr: { vi: "Nghe và viết các từ (cách nhau bằng dấu phẩy).", en: "Let's listen and write the words (separate with commas)." },
        items: [
          { id: "1", prompt: "1–5", lines: 1, wordSet: ["racconto", "riassunto", "passeggiare", "trascorrere", "viaggiare"], sample: "racconto, riassunto, passeggiare, trascorrere, viaggiare" },
          { id: "2", prompt: "6–10", lines: 1, wordSet: ["lettura", "spettacolo", "interessante", "caratteristico", "terribile"], sample: "lettura, spettacolo, interessante, caratteristico, terribile" },
          { id: "3", prompt: "11–15", lines: 1, wordSet: ["scrittore", "abbonamento", "parrucchiere", "appassionarsi", "preoccupazione"], sample: "scrittore, abbonamento, parrucchiere, appassionarsi, preoccupazione" },
        ],
      },
    },
    {
      type: "audio",
      src: "audio/u3-p58-ex21.mp3",
      title: "21",
      autoTranscript: true,
      transcript: "1. Come hai detto? 2. Vieni qui! 3. Vorresti venire con me? 4. Lo faresti? 5. Ti ho detto di no! 6. L'hai fatto tu? 7. Ci vado io! 8. Quando ci vedremo? 9. Non prendere quel libro! 10. Siete sicuri?",
    },
    {
      type: "exercise",
      ex: {
        id: "p058-ex21",
        inline: true,
        number: "21",
        icons: ["listen", "write"],
        kind: "choice",
        skill: "listening",
        refText: "audio",
        variant: "twoCol",
        instruction: "Ascoltiamo e scriviamo il punto interrogativo o esclamativo.",
        tr: { vi: "Nghe và điền dấu chấm hỏi hoặc dấu chấm than.", en: "Let's listen and write the question mark or the exclamation mark." },
        items: [
          { id: "1", prompt: "Come hai detto", options: ["?", "!"], answer: 0 },
          { id: "2", prompt: "Vieni qui", options: ["?", "!"], answer: 1 },
          { id: "3", prompt: "Vorresti venire con me", options: ["?", "!"], answer: 0 },
          { id: "4", prompt: "Lo faresti", options: ["?", "!"], answer: 0 },
          { id: "5", prompt: "Ti ho detto di no", options: ["?", "!"], answer: 1 },
          { id: "6", prompt: "L'hai fatto tu", options: ["?", "!"], answer: 0 },
          { id: "7", prompt: "Ci vado io", options: ["?", "!"], answer: 1 },
          { id: "8", prompt: "Quando ci vedremo", options: ["?", "!"], answer: 0 },
          { id: "9", prompt: "Non prendere quel libro", options: ["?", "!"], answer: 1 },
          { id: "10", prompt: "Siete sicuri", options: ["?", "!"], answer: 0 },
        ],
      },
    },
  ],
};

export default page;
