import type { BookPage } from "../../types";

/** Unità 4 · L'Italia a tavola — trang 79 (Scrittura e pronuncia, bài 19–22). */
const page: BookPage = {
  id: "p079",
  number: 79,
  unit: "4",
  unitTitle: "L'Italia a tavola",
  addedOn: "2026-10-07",
  sideTab: { unit: "U4", color: "#d8333a" },
  title: "Scrittura e pronuncia · s/z, m/n, b/p",
  runningHead: "Scrittura e pronuncia",
  blocks: [
    { type: "sectionTitle", text: "Scrittura e pronuncia" },
    { type: "audio", src: "audio/u4-p79-ex19.mp3", title: "19", autoTranscript: true, transcript: "1. delusione · 2. grazie · 3. ansia · 4. addizione · 5. giustizia · 6. pauroso · 7. calze · 8. senso · 9. senza · 10. prezioso · 11. esibizione · 12. consenso" },
    {
      type: "exercise",
      ex: {
        id: "p079-ex19",
        number: "19",
        icons: ["listen", "write"],
        kind: "fill",
        skill: "listening",
        refText: "audio",
        variant: "twoCol",
        instruction: "Ascoltiamo e completiamo le parole con s, z.",
        example: { q: "1. delu___ione", a: "delu***s***ione" },
        tr: { vi: "Nghe và điền s hoặc z vào chỗ trống.", en: "Let's listen and complete the words with s or z." },
        items: [
          { id: "2", prompt: "gra___ie", answers: ["z"] },
          { id: "3", prompt: "an___ia", answers: ["s"] },
          { id: "4", prompt: "addi___ione", answers: ["z"] },
          { id: "5", prompt: "giusti___ia", answers: ["z"] },
          { id: "6", prompt: "pauro___o", answers: ["s"] },
          { id: "7", prompt: "cal___e", answers: ["z"] },
          { id: "8", prompt: "___en___o", answers: ["s", "s"] },
          { id: "9", prompt: "___en___a", answers: ["s", "z"] },
          { id: "10", prompt: "pre___io___o", answers: ["z", "s"] },
          { id: "11", prompt: "e___ibi___ione", answers: ["s", "z"] },
          { id: "12", prompt: "con___en___o", answers: ["s", "s"] },
        ],
      },
    },
    { type: "audio", src: "audio/u4-p79-ex20.mp3", title: "20", autoTranscript: true, transcript: "1. contadino · 2. impegno · 3. lamponi · 4. ombrelli · 5. rompere · 6. condire · 7. pompiere · 8. inverno · 9. campana · 10. conto · 11. lampo · 12. temporale" },
    {
      type: "exercise",
      ex: {
        id: "p079-ex20",
        number: "20",
        icons: ["listen", "write"],
        kind: "fill",
        skill: "listening",
        refText: "audio",
        variant: "twoCol",
        instruction: "Ascoltiamo e completiamo le parole con m, n.",
        example: { q: "1. co___tadino", a: "co***n***tadino" },
        tr: { vi: "Nghe và điền m hoặc n vào chỗ trống.", en: "Let's listen and complete the words with m or n." },
        items: [
          { id: "2", prompt: "i___pegno", answers: ["m"] },
          { id: "3", prompt: "la___poni", answers: ["m"] },
          { id: "4", prompt: "o___brelli", answers: ["m"] },
          { id: "5", prompt: "ro___pere", answers: ["m"] },
          { id: "6", prompt: "co___dire", answers: ["n"] },
          { id: "7", prompt: "po___piere", answers: ["m"] },
          { id: "8", prompt: "i___verno", answers: ["n"] },
          { id: "9", prompt: "ca___pana", answers: ["m"] },
          { id: "10", prompt: "co___to", answers: ["n"] },
          { id: "11", prompt: "la___po", answers: ["m"] },
          { id: "12", prompt: "te___porale", answers: ["m"] },
        ],
      },
    },
    { type: "audio", src: "audio/u4-p79-ex21.mp3", title: "21", autoTranscript: true, transcript: "1. abile · 2. abbastanza · 3. apparire · 4. incalcolabile · 5. operazione · 6. abbattere · 7. impossibile · 8. babbuino · 9. opposto · 10. ape · 11. opprimere · 12. subito" },
    {
      type: "exercise",
      ex: {
        id: "p079-ex21",
        number: "21",
        icons: ["listen", "write"],
        kind: "fill",
        skill: "listening",
        refText: "audio",
        variant: "twoCol",
        instruction: "Ascoltiamo e completiamo le parole con b, bb, p, pp.",
        example: { q: "1. a___ile", a: "a***b***ile" },
        tr: { vi: "Nghe và điền b, bb, p hoặc pp vào chỗ trống.", en: "Let's listen and complete the words with b, bb, p or pp." },
        items: [
          { id: "2", prompt: "a___astanza", answers: ["bb"] },
          { id: "3", prompt: "a___arire", answers: ["pp"] },
          { id: "4", prompt: "incalcola___ile", answers: ["b"] },
          { id: "5", prompt: "o___erazione", answers: ["p"] },
          { id: "6", prompt: "a___attere", answers: ["bb"] },
          { id: "7", prompt: "impossi___ile", answers: ["b"] },
          { id: "8", prompt: "ba___uino", answers: ["bb"] },
          { id: "9", prompt: "o___osto", answers: ["pp"] },
          { id: "10", prompt: "a___e", answers: ["p"] },
          { id: "11", prompt: "o___rimere", answers: ["pp"] },
          { id: "12", prompt: "su___ito", answers: ["b"] },
        ],
      },
    },
    { type: "audio", src: "audio/u4-p79-ex22.mp3", title: "22", autoTranscript: true, transcript: "1. Ve lo facciamo assaggiare. 2. Puoi dirglielo tu. 3. Ce ne siamo andati. 4. Glielo dobbiamo dire. 5. Vuoi prenderne un po'? 6. Non me ne importa niente. 7. Vi ci portiamo. 8. Ce l'ha fatta." },
    {
      type: "exercise",
      ex: {
        id: "p079-ex22",
        number: "22",
        icons: ["listen", "write"],
        kind: "write",
        skill: "listening",
        refText: "audio",
        instruction: "Ascoltiamo e scriviamo le frasi.",
        tr: { vi: "Nghe và viết lại các câu.", en: "Let's listen and write the sentences." },
        items: [
          { id: "1", prompt: "1.", lines: 1, sample: "Ve lo facciamo assaggiare." },
          { id: "2", prompt: "2.", lines: 1, sample: "Puoi dirglielo tu." },
          { id: "3", prompt: "3.", lines: 1, sample: "Ce ne siamo andati." },
          { id: "4", prompt: "4.", lines: 1, sample: "Glielo dobbiamo dire." },
          { id: "5", prompt: "5.", lines: 1, sample: "Vuoi prenderne un po'?" },
          { id: "6", prompt: "6.", lines: 1, sample: "Non me ne importa niente." },
          { id: "7", prompt: "7.", lines: 1, sample: "Vi ci portiamo." },
          { id: "8", prompt: "8.", lines: 1, sample: "Ce l'ha fatta." },
        ],
      },
    },
  ],
};

export default page;
