import type { BookPage } from "../../types";

/** Unità 4 · L'Italia a tavola — trang 83 (Verifica). */
const page: BookPage = {
  id: "p083",
  number: 83,
  unit: "4",
  unitTitle: "L'Italia a tavola",
  title: "Verifica",
  addedOn: "2026-10-07",
  runningHead: "Verifica",
  tint: "blue",
  sideTab: { unit: "U4", color: "#2e8cc9" },
  blocks: [
    {
      type: "exercise",
      ex: {
        id: "p083-ex1",
        number: "1",
        kind: "fill",
        skill: "grammar",
        points: 10,
        instruction: "Scriviamo: completiamo le frasi con i pronomi.",
        example: { q: "Mi dai un succo di frutta? Certo, …… …… do subito.", a: "Certo, ***te lo*** do subito." },
        tr: { vi: "Cùng viết: hoàn thành câu với đại từ.", en: "Let's write: complete the sentences with the pronouns." },
        items: [
          { id: "1", prompt: "• Mi puoi prestare la tua forchetta? ○ No, non ___ ___ presto perché è sporca.", answers: ["te", "la"] },
          { id: "2", prompt: "• Chi vi lasciato le chiavi? ○ ___ ___ ha lasciate Pina.", answers: ["Ce", "le"] },
          { id: "3", prompt: "• Gli avete portato i giornali? ○ No, ancora non ___ abbiamo portati.", answers: ["glieli"] },
          { id: "4", prompt: "• Le hai detto la verità? ○ No, non ___ ho detta, non avevo il coraggio.", answers: ["gliel'|gliela"] },
          { id: "5", prompt: "Avevo prestato un libro a Daniela ma non ___ ha restituito.", answers: ["me l'|me lo"] },
          { id: "6", prompt: "• Hanno comprato il regalo a Beatrice? ○ Sì, ___ hanno comprato ieri.", answers: ["gliel'|glielo"] },
          { id: "7", prompt: "• Chi ha preparato la cena ai bambini? ○ ___ ha preparata la nonna.", answers: ["Gliel'|Gliela"] },
          { id: "8", prompt: "Anna gli ha chiesto un favore, ma lui non ___ ha fatto.", answers: ["gliel'|glielo"] },
          { id: "9", prompt: "• Quando ci presenti la tua fidanzata? ○ ___ presento sabato.", answers: ["Ve la"] },
          { id: "10", prompt: "• Vi hanno portato il pane? ○ No, non ___ ___ hanno portato.", answers: ["ce", "l'|lo"] },
        ],
      },
    },
    {
      type: "exercise",
      ex: {
        id: "p083-ex2",
        number: "2",
        kind: "match",
        skill: "grammar",
        points: 10,
        instruction: "Abbiniamo e completiamo le frasi con i pronomi.",
        tr: { vi: "Nối và hoàn thành câu với đại từ.", en: "Let's match and complete the sentences with the pronouns." },
        left: [
          { id: "1", text: "Siete riusciti a prendere il treno?" },
          { id: "2", text: "Sapete qualcosa di Piero?" },
          { id: "3", text: "Hai comprato la frutta?" },
          { id: "4", text: "La festa a casa di Michele era noiosa," },
          { id: "5", text: "Hai voglia di un gelato?" },
          { id: "6", text: "Arturo ha detto che viene domani," },
          { id: "7", text: "Andiamo al cinema," },
          { id: "8", text: "Hai una penna da prestarmi?" },
          { id: "9", text: "Ti ricordi di passare da Matteo?" },
          { id: "10", text: "Avete bisogno della macchina?" },
          { id: "11", text: "Per andare a Bologna" },
        ],
        right: [
          { id: "a", text: "ci metto due ore." },
          { id: "b", text: "così …… …… sono andato subito." },
          { id: "c", text: "No, grazie, non …… abbiamo bisogno." },
          { id: "d", text: "Sì, …… …… ho, come …… vuoi: nera o rossa?" },
          { id: "e", text: "Sì, …… …… ricordo, non ti preoccupare." },
          { id: "f", text: "No, …… …… sono dimenticato, scusa." },
          { id: "g", text: "Sì, …… …… abbiamo fatta." },
          { id: "h", text: "No, non …… sappiamo niente, perché?" },
          { id: "i", text: "che …… dici?" },
          { id: "l", text: "ma io non …… credo." },
          { id: "m", text: "Sì, …… ho proprio voglia! Come …… prendiamo?" },
        ],
        given: { "11": "a" },
        answer: { "1": "g", "2": "h", "3": "f", "4": "b", "5": "m", "6": "l", "7": "i", "8": "d", "9": "e", "10": "c", "11": "a" },
      },
    },
    {
      type: "exercise",
      ex: {
        id: "p083-ex2-pronomi",
        kind: "fill",
        skill: "grammar",
        instruction: "Completiamo con i pronomi.",
        tr: { vi: "Điền đại từ.", en: "Fill in the pronouns." },
        items: [
          { id: "b", prompt: "b. così ___ ___ sono andato subito.", answers: ["me", "ne"] },
          { id: "c", prompt: "c. No, grazie, non ___ abbiamo bisogno.", answers: ["ne"] },
          { id: "d", prompt: "d. Sì, ___ ___ ho, come ___ vuoi: nera o rossa?", answers: ["ce", "l'", "la"] },
          { id: "e", prompt: "e. Sì, ___ ___ ricordo, non ti preoccupare.", answers: ["me", "ne"] },
          { id: "f", prompt: "f. No, ___ ___ sono dimenticato, scusa.", answers: ["me", "ne"] },
          { id: "g", prompt: "g. Sì, ___ ___ abbiamo fatta.", answers: ["ce", "l'"] },
          { id: "h", prompt: "h. No, non ___ sappiamo niente, perché?", answers: ["ne"] },
          { id: "i", prompt: "i. che ___ dici?", answers: ["ne"] },
          { id: "l", prompt: "l. ma io non ___ credo.", answers: ["ci"] },
          { id: "m", prompt: "m. Sì, ___ ho proprio voglia! Come ___ prendiamo?", answers: ["ne", "lo"] },
        ],
      },
    },
    {
      type: "exercise",
      ex: {
        id: "p083-capace",
        kind: "fill",
        skill: "grammar",
        variant: "capace",
        instruction: "Ora sono capace di…",
        tr: { vi: "Bây giờ tôi có thể…", en: "Now I can…" },
        items: [
          { id: "1", lead: "usare i pronomi combinati:", prompt: "• Mi hai portato il libro? ○ Sì, ___ ___ ho portato.", answers: ["te", "l'|lo"] },
          { id: "2", lead: "usare ci con alcuni verbi:", prompt: "• Hai preparato la torta di mele? ○ No, non ___ sono riuscito.", answers: ["ci"] },
          { id: "3", lead: "usare ne partitivo:", prompt: "• Quanti cappuccini hai bevuto? ○ ___ ho bevuti due.", answers: ["Ne"] },
          { id: "4", lead: "usare ne con alcuni verbi:", prompt: "• Sai che Pino è un bravo cuoco? ○ Sì, ___ ___ sono accorto: cucina benissimo!", answers: ["me", "ne"] },
          { id: "5", lead: "usare alcuni verbi pronominali:", prompt: "Ieri non ___ ___ ho fatta a prendere l'autobus.", answers: ["ce", "l'"] },
        ],
      },
    },
  ],
};

export default page;
