import type { BookPage } from "../../types";

/** Unità 5 · Rispetti le regole? — trang 99 (Scrittura e pronuncia, bài 20–22). */
const page: BookPage = {
  id: "p099",
  number: 99,
  unit: "5",
  unitTitle: "Rispetti le regole?",
  addedOn: "2026-10-07",
  sideTab: { unit: "U5", color: "#d8333a" },
  title: "Scrittura e pronuncia · c/ce/ci/cie, g/ge/gi/gie",
  runningHead: "Scrittura e pronuncia",
  blocks: [
    { type: "sectionTitle", text: "Scrittura e pronuncia" },
    { type: "audio", src: "audio/u5-p99-ex20.mp3", title: "20", autoTranscript: true, transcript: "1. deficiente · 2. simpatico · 3. specie · 4. ufficio · 5. precedenza · 6. speciali · 7. particolari · 8. sufficiente · 9. minacce · 10. certo · 11. piacevole · 12. acido · 13. concetto · 14. decente · 15. cosciente · 16. pacco · 17. cucciolo · 18. mucca · 19. licenza · 20. goccia" },
    {
      type: "exercise",
      ex: {
        id: "p099-ex20",
        number: "20",
        icons: ["listen", "write"],
        kind: "fill",
        skill: "listening",
        refText: "audio",
        variant: "twoCol",
        instruction: "Ascoltiamo e completiamo le parole con c, ce, ci, cie.",
        example: { q: "1. defi___nte", a: "defi***cie***nte" },
        tr: { vi: "Nghe và điền c, ce, ci hoặc cie.", en: "Let's listen and complete the words with c, ce, ci, cie." },
        items: [
          { id: "2", prompt: "simpati___o", answers: ["c"] },
          { id: "3", prompt: "spe___", answers: ["cie"] },
          { id: "4", prompt: "uffi___o", answers: ["ci"] },
          { id: "5", prompt: "pre___denza", answers: ["ce"] },
          { id: "6", prompt: "spe___ali", answers: ["ci"] },
          { id: "7", prompt: "parti___olari", answers: ["c"] },
          { id: "8", prompt: "suffi___nte", answers: ["cie"] },
          { id: "9", prompt: "minac___", answers: ["ce"] },
          { id: "10", prompt: "___rto", answers: ["ce"] },
          { id: "11", prompt: "pia___vole", answers: ["ce"] },
          { id: "12", prompt: "a___do", answers: ["ci"] },
          { id: "13", prompt: "con___tto", answers: ["ce"] },
          { id: "14", prompt: "de___nte", answers: ["ce"] },
          { id: "15", prompt: "cos___ente", answers: ["cie"] },
          { id: "16", prompt: "pac___o", answers: ["c"] },
          { id: "17", prompt: "cuc___olo", answers: ["ci"] },
          { id: "18", prompt: "muc___a", answers: ["c"] },
          { id: "19", prompt: "li___nza", answers: ["ce"] },
          { id: "20", prompt: "goc___a", answers: ["ci"] },
        ],
      },
    },
    { type: "audio", src: "audio/u5-p99-ex21.mp3", title: "21", autoTranscript: true, transcript: "1. cugino · 2. guarire · 3. girasole · 4. gente · 5. gentilezza · 6. bugie · 7. assaggiare · 8. asparagi · 9. formaggio · 10. giorno · 11. gelato · 12. ciliegie · 13. fuga · 14. friggere · 15. egoismo · 16. dirigente · 17. digestione · 18. ragione · 19. pagella · 20. pagare" },
    {
      type: "exercise",
      ex: {
        id: "p099-ex21",
        number: "21",
        icons: ["listen", "write"],
        kind: "fill",
        skill: "listening",
        refText: "audio",
        variant: "twoCol",
        instruction: "Ascoltiamo e completiamo le parole con g, ge, gi, gie.",
        example: { q: "1. cu___no", a: "cu***gi***no" },
        tr: { vi: "Nghe và điền g, ge, gi hoặc gie.", en: "Let's listen and complete the words with g, ge, gi, gie." },
        items: [
          { id: "2", prompt: "___uarire", answers: ["g"] },
          { id: "3", prompt: "___rasole", answers: ["gi"] },
          { id: "4", prompt: "___nte", answers: ["ge"] },
          { id: "5", prompt: "___ntilezza", answers: ["ge"] },
          { id: "6", prompt: "bu___", answers: ["gie"] },
          { id: "7", prompt: "assag___are", answers: ["gi"] },
          { id: "8", prompt: "aspara___", answers: ["gi"] },
          { id: "9", prompt: "formag___o", answers: ["gi"] },
          { id: "10", prompt: "___orno", answers: ["gi"] },
          { id: "11", prompt: "___lato", answers: ["ge"] },
          { id: "12", prompt: "cilie___", answers: ["gie|ge"] },
          { id: "13", prompt: "fu___a", answers: ["g"] },
          { id: "14", prompt: "frig___re", answers: ["ge"] },
          { id: "15", prompt: "e___oismo", answers: ["g"] },
          { id: "16", prompt: "diri___nte", answers: ["ge"] },
          { id: "17", prompt: "di___stione", answers: ["ge"] },
          { id: "18", prompt: "ra___one", answers: ["gi"] },
          { id: "19", prompt: "pa___lla", answers: ["ge"] },
          { id: "20", prompt: "pa___are", answers: ["g"] },
        ],
      },
    },
    { type: "audio", src: "audio/u5-p99-ex22.mp3", title: "22", autoTranscript: true, transcript: "1. Falle vedere tutto quello che vuole! 2. Dimmelo ancora perché non ci credo! 3. Vattene, non ti voglio più vedere! 4. Non darglielo, non ne ha bisogno! 5. Ci faccia un favore! 6. Portiamoglielo, le farà piacere! 7. Stalle vicino, ha bisogno di te! 8. Al cinema? Vacci da solo, io non ne ho voglia! 9. • Volete un caffè? ○ Sì, grazie, fanne tre! 10. Dammi un consiglio!" },
    {
      type: "exercise",
      ex: {
        id: "p099-ex22",
        number: "22",
        icons: ["listen", "write"],
        kind: "fill",
        skill: "listening",
        refText: "audio",
        instruction: "Ascoltiamo e completiamo le frasi con le parole giuste.",
        example: { q: "1. …… vedere tutto quello che vuole!", a: "***Falle*** vedere tutto quello che vuole!" },
        tr: { vi: "Nghe và hoàn thành câu với từ thích hợp.", en: "Let's listen and complete the sentences with the right words." },
        items: [
          { id: "2", prompt: "2. ___ ancora perché non ci credo!", answers: ["Dimmelo"] },
          { id: "3", prompt: "3. ___, non ti voglio più vedere!", answers: ["Vattene"] },
          { id: "4", prompt: "4. ___ ___, non ne ha bisogno!", answers: ["Non", "darglielo"] },
          { id: "5", prompt: "5. ___ ___ un favore!", answers: ["Ci", "faccia"] },
          { id: "6", prompt: "6. ___, le farà piacere!", answers: ["Portiamoglielo"] },
          { id: "7", prompt: "7. ___ vicino, ha bisogno di te!", answers: ["Stalle"] },
          { id: "8", prompt: "8. Al cinema? ___ da solo, io non ne ho voglia!", answers: ["Vacci"] },
          { id: "9", prompt: "9. • Volete un caffè? ○ Sì, grazie, ___ tre!", answers: ["fanne"] },
          { id: "10", prompt: "10. ___ un consiglio!", answers: ["Dammi"] },
        ],
      },
    },
  ],
};

export default page;
