import type { BookPage } from "../../types";

/** Unità 6 · Cultura e società — trang 120 (Scrittura e pronuncia, bài 18–21). */
const page: BookPage = {
  id: "p120",
  number: 120,
  unit: "6",
  unitTitle: "Cultura e società",
  addedOn: "2026-10-08",
  sideTab: { unit: "U6", color: "#d8333a" },
  title: "Scrittura e pronuncia · chi/che/ghi/ghe, li/gli",
  blocks: [
    { type: "sectionTitle", text: "Scrittura e pronuncia" },
    { type: "audio", src: "audio/u6-p120-ex18.mp3", title: "18", autoTranscript: true, transcript: "1. Mi dia un chilo di pesche e uno di fichi. 2. Ieri sera siamo andati a cena con Michele, il nostro amico architetto. 3. Al mare Margherita, mentre raccoglieva le conchiglie, ha visto un granchio. 4. Il vecchio aveva molte rughe intorno agli occhi. 5. Abbiamo mangiato le orecchiette e i funghi. 6. Gli spaghetti sono pochi. 7. Le banche sono chiuse. 8. Nel laghetto c'erano larghe macchie d'olio." },
    {
      type: "exercise",
      ex: {
        id: "p120-ex18",
        number: "18",
        icons: ["listen", "write"],
        kind: "fill",
        skill: "listening",
        refText: "audio",
        instruction: "Ascoltiamo e completiamo le parole con chi, che, ghi, ghe.",
        example: { q: "1. Mi dia un ___lo di pes___ e uno di fi___.", a: "Mi dia un ***chi***lo di pes***che*** e uno di fi***chi***." },
        tr: { vi: "Nghe và điền chi, che, ghi hoặc ghe.", en: "Let's listen and complete the words with chi, che, ghi, ghe." },
        items: [
          { id: "2", prompt: "2. Ieri sera siamo andati a cena con Mi___le, il nostro amico ar___tetto.", answers: ["che", "chi"] },
          { id: "3", prompt: "3. Al mare Mar___rita, mentre raccoglieva le con___glie, ha visto un gran___o.", answers: ["ghe", "chi", "chi"] },
          { id: "4", prompt: "4. Il vec___o aveva molte ru___ intorno agli oc___.", answers: ["chi", "ghe", "chi"] },
          { id: "5", prompt: "5. Abbiamo mangiato le orec___tte e i fun___.", answers: ["chie", "ghi"] },
          { id: "6", prompt: "6. Gli spa___tti sono po___.", answers: ["ghe", "chi"] },
          { id: "7", prompt: "7. Le ban___ sono ___use.", answers: ["che", "chi"] },
          { id: "8", prompt: "8. Nel la___tto c'erano lar___ mac___e d'olio.", answers: ["ghe", "ghe", "chi"] },
        ],
      },
    },
    { type: "audio", src: "audio/u6-p120-ex19.mp3", title: "19", autoTranscript: true, transcript: "1. famiglia · 2. biglietto · 3. bottiglia · 4. Italia · 5. sveglia · 6. Sicilia · 7. Puglia · 8. veliero · 9. miliardo · 10. milione" },
    {
      type: "exercise",
      ex: {
        id: "p120-ex19",
        number: "19",
        icons: ["listen", "write"],
        kind: "fill",
        skill: "listening",
        refText: "audio",
        variant: "twoCol",
        instruction: "Ascoltiamo e completiamo le parole con li, gli.",
        example: { q: "1. fami___a", a: "fami***gli***a" },
        tr: { vi: "Nghe và điền li hoặc gli.", en: "Let's listen and complete the words with li, gli." },
        items: [
          { id: "2", prompt: "bi___etto", answers: ["gli"] },
          { id: "3", prompt: "botti___a", answers: ["gli"] },
          { id: "4", prompt: "Ita___a", answers: ["li"] },
          { id: "5", prompt: "sve___a", answers: ["gli"] },
          { id: "6", prompt: "Sici___a", answers: ["li"] },
          { id: "7", prompt: "Pu___a", answers: ["gli"] },
          { id: "8", prompt: "ve___ero", answers: ["li"] },
          { id: "9", prompt: "mi___ardo", answers: ["li"] },
          { id: "10", prompt: "mi___one", answers: ["li"] },
        ],
      },
    },
    { type: "audio", src: "audio/u6-p120-ex20.mp3", title: "20", autoTranscript: true, transcript: "1. daremmo · 2. porrete · 3. tradurrete · 4. vorrai · 5. vedrei · 6. faremmo · 7. potrete · 8. direste" },
    {
      type: "exercise",
      ex: {
        id: "p120-ex20",
        number: "20",
        icons: ["listen", "write"],
        kind: "choice",
        inline: true,
        skill: "listening",
        refText: "audio",
        instruction: "Ascoltiamo e sottolineiamo la parola giusta.",
        example: { q: "1. daremo / daremmo", a: "***daremmo***" },
        tr: { vi: "Nghe và gạch chân từ đúng.", en: "Let's listen and underline the right word." },
        items: [
          { id: "2", prompt: "", options: ["porrete", "porreste"], answer: 0 },
          { id: "3", prompt: "", options: ["tradurreste", "tradurrete"], answer: 1 },
          { id: "4", prompt: "", options: ["vorrai", "vorrei"], answer: 0 },
          { id: "5", prompt: "", options: ["vedrei", "vedrai"], answer: 0 },
          { id: "6", prompt: "", options: ["faremo", "faremmo"], answer: 1 },
          { id: "7", prompt: "", options: ["potrete", "potreste"], answer: 0 },
          { id: "8", prompt: "", options: ["direste", "direte"], answer: 0 },
        ],
      },
    },
    {
      type: "exercise",
      ex: {
        id: "p120-ex21",
        number: "21",
        icons: ["write"],
        kind: "write",
        skill: "writing",
        instruction: "Scriviamo: completiamo le parole.",
        example: { q: "1. L'un_ _ _sità _ _ _liana ha molti st_ _enti fuori co_so.", a: "***L'università italiana ha molti studenti fuori corso.***" },
        tr: { vi: "Cùng viết: điền chữ còn thiếu và chép lại cả câu.", en: "Let's write: complete the words and write out the whole sentence." },
        items: [
          { id: "2", prompt: "2. L'eco___mia it___ana s__rà più fo__te nei pros___mi an__i.", lines: 1, sample: "L'economia italiana sarà più forte nei prossimi anni." },
          { id: "3", prompt: "3. I poli___ci fa__no mol__e pro___se per il f__turo.", lines: 1, sample: "I politici faranno molte proposte per il futuro." },
          { id: "4", prompt: "4. Negli osp___li i potre__o av__re li__te d'att__sa m__no lun__e.", lines: 1, sample: "Negli ospedali i pazienti potranno avere liste d'attesa meno lunghe." },
          { id: "5", prompt: "5. Le azi___de dovr__nno assum__e più gio__ani.", lines: 1, sample: "Le aziende dovranno assumere più giovani." },
          { id: "6", prompt: "6. Gli ita__iani usera__no se__pre di più Inte__et per fa__e ac__uisti.", lines: 1, sample: "Gli italiani useranno sempre di più Internet per fare acquisti." },
          { id: "7", prompt: "7. Tu__ti i cit__dini dovre___ro ave__e rispe__o dell'am___nte.", lines: 1, sample: "Tutti i cittadini dovranno avere rispetto dell'ambiente." },
        ],
      },
    },
  ],
};

export default page;
