import type { BookPage } from "../../types";

/** Unità 8 · Andiamo in edicola! — trang 159 (Scrittura e pronuncia, bài 19–22: sci/sce/scie, sc). */
const page: BookPage = {
  id: "p159",
  number: 159,
  unit: "8",
  unitTitle: "Andiamo in edicola!",
  addedOn: "2026-10-08",
  sideTab: { unit: "U8", color: "#d8333a" },
  title: "Scrittura e pronuncia · sci/sce/scie",
  blocks: [
    { type: "sectionTitle", text: "Scrittura e pronuncia" },
    { type: "audio", src: "audio/u8-p159-ex19.mp3", title: "19", autoTranscript: true, transcript: "1. scettro · 2. asciugare · 3. sceicco · 4. sciocco · 5. scena · 6. scienza · 7. palcoscenico · 8. prosciutto · 9. coscienza · 10. pesce · 11. ascensore · 12. scientifico" },
    {
      type: "exercise",
      ex: {
        id: "p159-ex19",
        number: "19",
        icons: ["listen", "write"],
        kind: "fill",
        skill: "listening",
        refText: "audio",
        variant: "twoCol",
        instruction: "Ascoltiamo e completiamo le parole con sci, sce, scie.",
        example: { q: "1. ___ttro", a: "***sce***ttro" },
        tr: { vi: "Nghe và điền sci, sce hoặc scie vào các từ.", en: "Let's listen and complete the words with sci, sce, scie." },
        items: [
          { id: "2", prompt: "2. a___ugare", answers: ["sci"] },
          { id: "3", prompt: "3. ___icco", answers: ["sce"] },
          { id: "4", prompt: "4. ___occo", answers: ["sci"] },
          { id: "5", prompt: "5. ___na", answers: ["sce"] },
          { id: "6", prompt: "6. ___nza", answers: ["scie"] },
          { id: "7", prompt: "7. palco___nico", answers: ["sce"] },
          { id: "8", prompt: "8. pro___utto", answers: ["sci"] },
          { id: "9", prompt: "9. co___nza", answers: ["scie"] },
          { id: "10", prompt: "10. pe___", answers: ["sce"] },
          { id: "11", prompt: "11. a___nsore", answers: ["sce"] },
          { id: "12", prompt: "12. ___ntifico", answers: ["scie"] },
        ],
      },
    },
    { type: "audio", src: "audio/u8-p159-ex20.mp3", title: "20", autoTranscript: true, transcript: "1. sciogliere · 2. scuola · 3. sciare · 4. scudo · 5. pascolo · 6. scappare · 7. scomodo · 8. scippare · 9. nascita · 10. asciutto · 11. scendere · 12. scienziato" },
    {
      type: "exercise",
      ex: {
        id: "p159-ex20",
        number: "20",
        icons: ["listen", "write"],
        kind: "fill",
        skill: "listening",
        refText: "audio",
        variant: "twoCol",
        instruction: "Ascoltiamo e scriviamo le parole.",
        tr: { vi: "Nghe và viết các từ.", en: "Let's listen and write the words." },
        items: [
          { id: "1", prompt: "1. ___", answers: ["sciogliere"] },
          { id: "2", prompt: "2. ___", answers: ["scuola"] },
          { id: "3", prompt: "3. ___", answers: ["sciare"] },
          { id: "4", prompt: "4. ___", answers: ["scudo"] },
          { id: "5", prompt: "5. ___", answers: ["pascolo"] },
          { id: "6", prompt: "6. ___", answers: ["scappare"] },
          { id: "7", prompt: "7. ___", answers: ["scomodo"] },
          { id: "8", prompt: "8. ___", answers: ["scippare"] },
          { id: "9", prompt: "9. ___", answers: ["nascita"] },
          { id: "10", prompt: "10. ___", answers: ["asciutto"] },
          { id: "11", prompt: "11. ___", answers: ["scendere"] },
          { id: "12", prompt: "12. ___", answers: ["scienziato"] },
        ],
      },
    },
    { type: "audio", src: "audio/u8-p159-ex21.mp3", title: "21", autoTranscript: true, transcript: "1. Voglio che tu faccia quello che ti ho detto. 2. Non occorre che tu me lo dica ancora: l'ho già fatto. 3. È importante che lei scelga bene il suo corso. 4. È meglio che voi proponiate un'altra soluzione. 5. Bisogna che tolgano subito quella macchina dalla strada. 6. Mi dispiace che lui debba andarsene. 7. Credo che possiate venire con noi. 8. Pensiamo che tutti sappiano la verità." },
    {
      type: "exercise",
      ex: {
        id: "p159-ex21",
        number: "21",
        icons: ["listen", "write"],
        kind: "fill",
        skill: "listening",
        refText: "audio",
        instruction: "Ascoltiamo e completiamo le frasi con le parole giuste.",
        tr: { vi: "Nghe và hoàn thành câu với các từ đúng.", en: "Let's listen and complete the sentences with the right words." },
        items: [
          { id: "1", prompt: "1. ___ che tu ___ quello che ti ho detto.", answers: ["Voglio", "faccia"] },
          { id: "2", prompt: "2. Non ___ che tu me lo ___ ancora: l'ho già fatto.", answers: ["occorre", "dica"] },
          { id: "3", prompt: "3. È importante che lei ___ bene il suo corso.", answers: ["scelga"] },
          { id: "4", prompt: "4. È meglio che voi ___ un'altra soluzione.", answers: ["proponiate"] },
          { id: "5", prompt: "5. ___ che ___ subito quella macchina dalla strada.", answers: ["Bisogna", "tolgano"] },
          { id: "6", prompt: "6. Mi ___ che lui ___ andarsene.", answers: ["dispiace", "debba"] },
          { id: "7", prompt: "7. Credo che ___ venire con noi.", answers: ["possiate"] },
          { id: "8", prompt: "8. Pensiamo che tutti ___ la verità.", answers: ["sappiano"] },
        ],
      },
    },
    {
      type: "exercise",
      ex: {
        id: "p159-ex22",
        number: "22",
        icons: ["write"],
        kind: "fill",
        skill: "writing",
        variant: "twoCol",
        instruction: "Scriviamo: correggiamo le parole se necessario.",
        example: { q: "1. reddattore →", a: "***redattore***" },
        tr: { vi: "Cùng viết: sửa chính tả các từ nếu cần.", en: "Let's write: correct the words if necessary." },
        items: [
          { id: "2", prompt: "2. inviato → ___", answers: ["inviato"] },
          { id: "3", prompt: "3. cronasta → ___", answers: ["cronista"] },
          { id: "4", prompt: "4. articolo di fundo → ___", answers: ["articolo di fondo"] },
          { id: "5", prompt: "5. rubbrica → ___", answers: ["rubrica"] },
          { id: "6", prompt: "6. notizziario → ___", answers: ["notiziario"] },
          { id: "7", prompt: "7. disegniatore → ___", answers: ["disegnatore"] },
          { id: "8", prompt: "8. sommario → ___", answers: ["sommario"] },
          { id: "9", prompt: "9. publicità → ___", answers: ["pubblicità"] },
          { id: "10", prompt: "10. polittica estera → ___", answers: ["politica estera"] },
        ],
      },
    },
  ],
};

export default page;
