import type { BookPage } from "../../types";

/** Unità 9 · Facciamo un'intervista! — trang 181 (Scrittura e pronuncia, bài 20–22: le doppie). */
const page: BookPage = {
  id: "p181",
  number: 181,
  unit: "9",
  unitTitle: "Facciamo un'intervista!",
  addedOn: "2026-10-08",
  sideTab: { unit: "U9", color: "#d8333a" },
  title: "Scrittura e pronuncia · Le doppie",
  blocks: [
    { type: "sectionTitle", text: "Scrittura e pronuncia" },
    { type: "audio", src: "audio/u9-p181-ex20.mp3", title: "20", autoTranscript: true, transcript: "1. carabiniere · 2. abbastanza · 3. abitazione · 4. mobile · 5. accumulare · 6. sacco · 7. zucchero · 8. specchio · 9. abbraccio · 10. treccia · 11. mediocre · 12. addirittura · 13. raddoppiare · 14. afferrare · 15. efficace · 16. difendere · 17. ragione · 18. agitato · 19. passeggiare · 20. religione" },
    {
      type: "exercise",
      ex: {
        id: "p181-ex20",
        number: "20",
        icons: ["listen", "write"],
        kind: "choice",
        inline: true,
        skill: "listening",
        refText: "audio",
        variant: "twoCol",
        instruction: "Ascoltiamo e sottolineiamo la parola giusta.",
        example: { q: "1. carabiniere / carabbiniere", a: "***carabiniere***" },
        tr: { vi: "Nghe và gạch chân từ viết đúng.", en: "Let's listen and underline the right word." },
        items: [
          { id: "2", prompt: "", options: ["abbastanza", "abastanza"], answer: 0 },
          { id: "3", prompt: "", options: ["abitazione", "abbitazione"], answer: 0 },
          { id: "4", prompt: "", options: ["mobile", "mobbile"], answer: 0 },
          { id: "5", prompt: "", options: ["accumulare", "acumulare"], answer: 0 },
          { id: "6", prompt: "", options: ["saco", "sacco"], answer: 1 },
          { id: "7", prompt: "", options: ["zuchero", "zucchero"], answer: 1 },
          { id: "8", prompt: "", options: ["specchio", "spechio"], answer: 0 },
          { id: "9", prompt: "", options: ["abbraccio", "abbracio"], answer: 0 },
          { id: "10", prompt: "", options: ["treccia", "trecia"], answer: 0 },
          { id: "11", prompt: "", options: ["mediocre", "meddiocre"], answer: 0 },
          { id: "12", prompt: "", options: ["addirittura", "adirittura"], answer: 0 },
          { id: "13", prompt: "", options: ["raddoppiare", "radoppiare"], answer: 0 },
          { id: "14", prompt: "", options: ["afferrare", "aferrare"], answer: 0 },
          { id: "15", prompt: "", options: ["eficace", "efficace"], answer: 1 },
          { id: "16", prompt: "", options: ["difendere", "diffendere"], answer: 0 },
          { id: "17", prompt: "", options: ["ragione", "raggione"], answer: 0 },
          { id: "18", prompt: "", options: ["aggitato", "agitato"], answer: 1 },
          { id: "19", prompt: "", options: ["passeggiare", "passegiare"], answer: 0 },
          { id: "20", prompt: "", options: ["religione", "religgione"], answer: 0 },
        ],
      },
    },
    { type: "audio", src: "audio/u9-p181-ex21.mp3", title: "21", autoTranscript: true, transcript: "1. allegro · 2. illuminare · 3. filo · 4. ammettere · 5. immenso · 6. diamante · 7. ministro · 8. ginnastica · 9. innamorarsi · 10. sapone · 11. scappare · 12. applauso · 13. acqua · 14. acquerello · 15. aquila · 16. acquisto · 17. errore · 18. arrivare · 19. orrendo · 20. spiritoso · 21. accelerare" },
    {
      type: "exercise",
      ex: {
        id: "p181-ex21",
        number: "21",
        icons: ["listen", "write"],
        kind: "choice",
        inline: true,
        skill: "listening",
        refText: "audio",
        variant: "twoCol",
        instruction: "Ascoltiamo e sottolineiamo la parola giusta.",
        example: { q: "1. allegro / alegro", a: "***allegro***" },
        tr: { vi: "Nghe và gạch chân từ viết đúng.", en: "Let's listen and underline the right word." },
        items: [
          { id: "2", prompt: "", options: ["iluminare", "illuminare"], answer: 1 },
          { id: "3", prompt: "", options: ["filo", "fillo"], answer: 0 },
          { id: "4", prompt: "", options: ["ammettere", "amettere"], answer: 0 },
          { id: "5", prompt: "", options: ["immenso", "imenso"], answer: 0 },
          { id: "6", prompt: "", options: ["diamante", "diammante"], answer: 0 },
          { id: "7", prompt: "", options: ["ministro", "minnistro"], answer: 0 },
          { id: "8", prompt: "", options: ["ginnastica", "ginastica"], answer: 0 },
          { id: "9", prompt: "", options: ["innamorarsi", "inamorarsi"], answer: 0 },
          { id: "10", prompt: "", options: ["sapone", "sappone"], answer: 0 },
          { id: "11", prompt: "", options: ["scappare", "scapare"], answer: 0 },
          { id: "12", prompt: "", options: ["applauso", "aplauso"], answer: 0 },
          { id: "13", prompt: "", options: ["aqua", "acqua"], answer: 1 },
          { id: "14", prompt: "", options: ["acquerello", "aquerello"], answer: 0 },
          { id: "15", prompt: "", options: ["aquila", "acquila"], answer: 0 },
          { id: "16", prompt: "", options: ["acquisto", "aquisto"], answer: 0 },
          { id: "17", prompt: "", options: ["errore", "erore"], answer: 0 },
          { id: "18", prompt: "", options: ["arrivare", "arivare"], answer: 0 },
          { id: "19", prompt: "", options: ["orrendo", "orendo"], answer: 0 },
          { id: "20", prompt: "", options: ["spiritoso", "spirritoso"], answer: 0 },
          { id: "21", prompt: "", options: ["accelerare", "accellerare"], answer: 0 },
        ],
      },
    },
    {
      type: "exercise",
      ex: {
        id: "p181-ex22",
        number: "22",
        icons: ["read", "write"],
        kind: "fill",
        skill: "writing",
        variant: "twoCol",
        instruction: "Leggiamo e correggiamo se necessario.",
        example: { q: "1. orechie →", a: "***orecchie***" },
        tr: { vi: "Đọc và sửa chính tả nếu cần.", en: "Let's read and correct if necessary." },
        items: [
          { id: "2", prompt: "2. terribile → ___", answers: ["terribile"] },
          { id: "3", prompt: "3. preoccupato → ___", answers: ["preoccupato"] },
          { id: "4", prompt: "4. facia → ___", answers: ["faccia"] },
          { id: "5", prompt: "5. attaccare → ___", answers: ["attaccare"] },
          { id: "6", prompt: "6. immagginare → ___", answers: ["immaginare"] },
          { id: "7", prompt: "7. caminare → ___", answers: ["camminare"] },
          { id: "8", prompt: "8. ingrasare → ___", answers: ["ingrassare"] },
          { id: "9", prompt: "9. possedere → ___", answers: ["possedere"] },
          { id: "10", prompt: "10. assasino → ___", answers: ["assassino"] },
          { id: "11", prompt: "11. soprattutto → ___", answers: ["soprattutto"] },
          { id: "12", prompt: "12. frittata → ___", answers: ["frittata"] },
          { id: "13", prompt: "13. brillante → ___", answers: ["brillante"] },
          { id: "14", prompt: "14. avvocato → ___", answers: ["avvocato"] },
          { id: "15", prompt: "15. motivvo → ___", answers: ["motivo"] },
          { id: "16", prompt: "16. azurro → ___", answers: ["azzurro"] },
          { id: "17", prompt: "17. gentilezza → ___", answers: ["gentilezza"] },
          { id: "18", prompt: "18. vizzio → ___", answers: ["vizio"] },
          { id: "19", prompt: "19. amicizzia → ___", answers: ["amicizia"] },
          { id: "20", prompt: "20. pazzia → ___", answers: ["pazzia"] },
        ],
      },
    },
  ],
};

export default page;
