import type { BookPage } from "../../types";

/** Unità 10 · Tradizioni popolari — trang 200 (Scrittura e pronuncia, bài 17–19). */
const page: BookPage = {
  id: "p200",
  number: 200,
  unit: "10",
  unitTitle: "Tradizioni popolari",
  addedOn: "2026-10-08",
  sideTab: { unit: "U10", color: "#d8333a" },
  title: "Scrittura e pronuncia · Doppie e suoni",
  blocks: [
    { type: "sectionTitle", text: "Scrittura e pronuncia" },
    { type: "audio", src: "audio/u10-p200-ex17.mp3", title: "17", autoTranscript: true, transcript: "1. sacro · 2. profano · 3. protettore · 4. liquefazione · 5. cerimonia · 6. processione · 7. festeggiare · 8. festaiolo · 9. ricorrenza · 10. parrocchia · 11. parrucca · 12. commemorazione · 13. patrono · 14. pasquale" },
    {
      type: "exercise",
      ex: {
        id: "p200-ex17",
        number: "17",
        icons: ["listen", "write"],
        kind: "choice",
        inline: true,
        skill: "listening",
        refText: "audio",
        variant: "twoCol",
        instruction: "Ascoltiamo e sottolineiamo le parole giuste.",
        tr: { vi: "Nghe và gạch chân các từ viết đúng.", en: "Let's listen and underline the right words." },
        items: [
          { id: "1", prompt: "", options: ["sacro", "sagro"], answer: 0 },
          { id: "2", prompt: "", options: ["profano", "profanno"], answer: 0 },
          { id: "3", prompt: "", options: ["prottettore", "protettore"], answer: 1 },
          { id: "4", prompt: "", options: ["liquefazione", "licquefazione"], answer: 0 },
          { id: "5", prompt: "", options: ["cerimonia", "scerimonia"], answer: 0 },
          { id: "6", prompt: "", options: ["proccessione", "processione"], answer: 1 },
          { id: "7", prompt: "", options: ["festegiare", "festeggiare"], answer: 1 },
          { id: "8", prompt: "", options: ["festaiolo", "festagliolo"], answer: 0 },
          { id: "9", prompt: "", options: ["ricorrenza", "ricorenza"], answer: 0 },
          { id: "10", prompt: "", options: ["parrocchia", "parrochia"], answer: 0 },
          { id: "11", prompt: "", options: ["parrucca", "parruca"], answer: 0 },
          { id: "12", prompt: "", options: ["commemorazione", "comemorazione"], answer: 0 },
          { id: "13", prompt: "", options: ["patrono", "padrono"], answer: 0 },
          { id: "14", prompt: "", options: ["pasquale", "pascquale"], answer: 0 },
        ],
      },
    },
    { type: "audio", src: "audio/u10-p200-ex18.mp3", title: "18", autoTranscript: true, transcript: "1. cero · 2. drappo · 3. avvincente · 4. travestirsi · 5. rito · 6. palio · 7. anniversario · 8. sfilata · 9. coriandoli · 10. chiacchiere · 11. frittella · 12. centenario · 13. inaugurazione · 14. quaresima" },
    {
      type: "exercise",
      ex: {
        id: "p200-ex18",
        number: "18",
        icons: ["listen", "write"],
        kind: "choice",
        inline: true,
        skill: "listening",
        refText: "audio",
        variant: "twoCol",
        instruction: "Ascoltiamo e sottolineiamo le parole giuste.",
        tr: { vi: "Nghe và gạch chân các từ viết đúng.", en: "Let's listen and underline the right words." },
        items: [
          { id: "1", prompt: "", options: ["cero", "c'ero"], answer: 0 },
          { id: "2", prompt: "", options: ["drappo", "trappo"], answer: 0 },
          { id: "3", prompt: "", options: ["avvingente", "avvincente"], answer: 1 },
          { id: "4", prompt: "", options: ["travestirzi", "travestirsi"], answer: 1 },
          { id: "5", prompt: "", options: ["rito", "ritto"], answer: 0 },
          { id: "6", prompt: "", options: ["pallio", "palio"], answer: 1 },
          { id: "7", prompt: "", options: ["anniversario", "aniversario"], answer: 0 },
          { id: "8", prompt: "", options: ["sfilada", "sfilata"], answer: 1 },
          { id: "9", prompt: "", options: ["coriantoli", "coriandoli"], answer: 1 },
          { id: "10", prompt: "", options: ["chiacchiere", "chiacciere"], answer: 0 },
          { id: "11", prompt: "", options: ["frittella", "fritella"], answer: 0 },
          { id: "12", prompt: "", options: ["centenario", "centennario"], answer: 0 },
          { id: "13", prompt: "", options: ["inaugurazione", "innaugurazione"], answer: 0 },
          { id: "14", prompt: "", options: ["quaresima", "guaresima"], answer: 0 },
        ],
      },
    },
    { type: "audio", src: "audio/u10-p200-ex19.mp3", title: "19", autoTranscript: true, transcript: "1. Nel Palio di Siena ci sono 17 contrade. 2. Nel gioco del calcio fiorentino si sfidano 4 quartieri. 3. La Giostra della Quintana ha un fascino antico. 4. Il miracolo di San Gennaro è famosissimo. 5. Si incontrano molte persone alla festa dei Ceri. 6. Gli italiani celebrano molti anniversari. 7. Il Carnevale di Venezia attira numerosissimi turisti." },
    {
      type: "exercise",
      ex: {
        id: "p200-ex19",
        number: "19",
        icons: ["listen", "write"],
        kind: "write",
        skill: "listening",
        refText: "audio",
        instruction: "Ascoltiamo e scriviamo le frasi.",
        tr: { vi: "Nghe và viết lại các câu.", en: "Let's listen and write the sentences." },
        items: [
          { id: "1", prompt: "", lines: 2, sample: "Nel Palio di Siena ci sono 17 contrade." },
          { id: "2", prompt: "", lines: 2, sample: "Nel gioco del calcio fiorentino si sfidano 4 quartieri." },
          { id: "3", prompt: "", lines: 2, sample: "La Giostra della Quintana ha un fascino antico." },
          { id: "4", prompt: "", lines: 2, sample: "Il miracolo di San Gennaro è famosissimo." },
          { id: "5", prompt: "", lines: 2, sample: "Si incontrano molte persone alla festa dei Ceri." },
          { id: "6", prompt: "", lines: 2, sample: "Gli italiani celebrano molti anniversari." },
          { id: "7", prompt: "", lines: 2, sample: "Il Carnevale di Venezia attira numerosissimi turisti." },
        ],
      },
    },
  ],
};

export default page;
